eureka:
  client:
    serviceUrl:
      defaultZone: http://10.70.22.8:18761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8083

spring:
  application:
    name: roger-service-vote
#  mvc:
#    view:
#      prefix: /
#      suffix: .html
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    servlet:
      content-type: text/html
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/roger_dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=true
    #url: jdbc:mysql://10.60.2.101:3306/yofc_mobile_cb
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: 10.70.18.111
    port: 26379
    password: redis123456
    #: 127.0.0.1
    #port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 100
        max-wait: 2000
        max-idle: 500
        min-idle: 8
    timeout:  10000
#  kafka:
#    bootstrap-servers: 10.70.18.109:9092
#    consumer:
#      group-id: mygroup
#  data:
#    mongodb:
#      host: 10.70.18.111
#      port: 27018
#      username: cb_dev
#      password: yofc_app123$
#      database: yofccb_dev

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/subject/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.yofc.dal.subject.entity  # 注意：对应实体类的路径

#pagehelper分页插件
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql

logging:
  level:
    com.yofc.dal : debug

web:
  pageSize: 10
  dropPageSize: 10
  errorPage:
    PAGE404: "/index"
    PAGE500: "/index"
    PAGE40X: "/index"

cbJms:
  enable: false
  messageTopic: cbMessageTopic

#调用微信信息接口
cbServer:
  weburl: http://127.0.0.1:9999
  wexin:
    message:
      debug: true
      remoteUrl: http://www.yofcqywx.top:9094/tongshiba/push_message.php?userid=2806&title={title}&description={description}&url={url}
      remoteUrl4Dept: http://www.yofcqywx.top:9094/tongshiba/push_dept_message.php?deptid={deptId}&title={title}&description={description}&url={url}
      readTimeout: 5000
      connectTimeout: 5000